version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: vlkazmin/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    env_file: .env
    image: vlkazmin/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: vlkazmin/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media
